version: "3.9"
services:
  taskflow-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskflow:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes: 
      - ../..:/app
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:5002:5002"
    networks:
      - taskflow

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - dbdata:/data/db
    networks:
      - taskflow

volumes:
  dbdata:

networks:
    taskflow:
       external: true