version: "3.9"
services:
  taskflow-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskflow:latest
    restart: always
    volumes: 
      - ../..:/app
      - ./root:/root # For SSH and gitconfig
    ports:
      - "127.0.0.1:9229:9229" # debug of hub
      - "127.0.0.1:9230:9230" # debug of nodejs
    networks:
      - web-proxy

networks:
    web-proxy:
       external: true
