version: "3.9"
services:
  taskflow:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskflow:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes: 
      - ../..:/app/taskflow
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5001:5001"
