version: "3.9"
services:
  taskflow:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskflow:latest
    volumes: 
      - ../../..:/app/
      - ./root:/root # For SSH and gitconfig
    networks:
      - web-proxy

networks:
    web-proxy:
       external: true