version: "3.9"
services:
  taskflow-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskflow:latest
    restart: always
    volumes: 
      - ../..:/app
      - ./root:/root # For SSH and gitconfig
    ports:
      - "127.0.0.1:9229:9229" # debug of hub
      - "127.0.0.1:9230:9230" # debug of nodejs
    networks:
      - web-proxy

#  mongodb:
#    image: mongodb/mongodb-community-server:latest
#    ports:
#      - '127.0.0.1:27017:27017'
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=user
#      - MONGO_INITDB_ROOT_PASSWORD=pass
#    volumes:
#      - dbdata:/data/db
#    networks:
#      - web-proxy
#
#volumes:
#  dbdata:

networks:
    web-proxy:
       external: true
