version: "3.9"
services:
  taskflow-react:
    #image: localhost:5000/taskflow-prod:latest
    image: taskflow-prod:latest
    volumes:
      - ../../processor/react:/app/processor/react
      - ../../shared:/app/shared
    entrypoint: ["/entrypoint-react.sh"]
    environment:
      - REACT_APP_TASKHUB_URL=http://localhost:5001/hub
      - REACT_APP_LABEL=T@skFlow
    depends_on:
      - taskflow-hub
    networks:
      - web-proxy
  taskflow-nodejs:
    #image: localhost:5000/taskflow-prod:latest
    image: taskflow-prod:latest
    volumes:
      - ../../processor/nodejs:/app/processor/nodejs
      - ../../shared:/app/shared
    entrypoint: ["/entrypoint-nodejs.sh"]
    environment:
      - TASKHUB_URL=http://localhost:5001/hub
    networks:
      - web-proxy
    depends_on:
      - taskflow-hub
  taskflow-hub:
    #image: localhost:5000/taskflow-prod:latest
    image: taskflow-prod:latest
    volumes:
      - ../../hub:/app/hub
      - ../../shared:/app/shared
    entrypoint: ["/entrypoint-hub.sh"]
    networks:
      - web-proxy

networks:
  web-proxy:
    external: true

