version: "3.9"
services:
  chat2flow-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat2flow-prod:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes: 
      - ..:/app/chat2flow
    networks:
      - web-proxy

networks:
    web-proxy:
       external: true
