version: "3.9"
services:
  chat2flow:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: chat2flow:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:5000:5000"
