version: "3.9"
services:
  chat2flow:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        CACHEBUSTER: ${CACHEBUSTER}
    image: chat2flow:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
